# Generated by Django 3.1.14 on 2022-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('post_date', models.AutoField(primary_key=True, serialize=False)),
                ('post_top30', models.CharField(max_length=45)),
                ('post_title', models.CharField(max_length=45)),
                ('post_rate', models.CharField(max_length=45)),
                ('post_content', models.CharField(max_length=45)),
                ('post_tags', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stockdata',
                'managed': False,
            },
        ),
    ]
