# Generated by Django 4.0.3 on 2022-04-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0002_stockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
